import React,{useState,useEffect,useRef,useCallback,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Sun, Moon, Activity, Search, Plus, MoreVertical, Shield, Check, AlertCircle, Gamepad2, SlidersHorizontal, Download, FolderOpen, Settings as SettingsIcon, Upload, X, Copy, Trash2, FileJson, RefreshCw, ChevronRight, Eye, CircleHelp} from 'lucide-react';
import type {Snapshot,Draft,Profile,Device,Picker} from './types';
import {clone,makeDraft,dirty,visibility,setVisibility,devicesFor,deviceRows,filterDeviceRows,validation,pendingCount,same} from './model';
import {ApplicationIcon,DeviceIcon} from './icons';
import {classifyDevice,controllerLabel} from './device-kind';
import './style.css';

const api=window.hidHide;

const basename=(p:string)=>p.split(/[\\/]/).pop()||p;
function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const before=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{ref.current?.close();before?.focus();};},[]);
 return <dialog className={wide?'wide':''} ref={ref} onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="dialog-heading"><header><h2 id="dialog-heading">{title}</h2><button className="icon" aria-label="Close dialog" onClick={onClose}><X size={19}/></button></header>{children}</dialog>;
}
function App({initialTheme}:{initialTheme:'light'|'dark'}){
 const [theme,setTheme]=useState(initialTheme),[themeSaving,setThemeSaving]=useState(false),[themeError,setThemeError]=useState('');
 async function toggleTheme(){if(themeSaving)return;setThemeSaving(true);setThemeError('');try{const next=await api.setTheme(theme==='dark'?'light':'dark');document.documentElement.dataset.theme=next;setTheme(next);}catch{setThemeError('Could not save appearance. Please try again.');}finally{setThemeSaving(false);}}
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[draft,setDraft]=useState<Draft|null>(null),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[connectionAttempted,setConnectionAttempted]=useState(false);
 const [hideDisconnected,setHideDisconnected]=useState(()=>{try{return localStorage.getItem('hide-disconnected')==='1';}catch{return false;}});
 const [hideNonControllers,setHideNonControllers]=useState(()=>{try{return localStorage.getItem('hide-non-controllers')==='1';}catch{return false;}});
 const [error,setError]=useState(''),[connectionError,setConnectionError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[modal,setModal]=useState(''),[deviceInfo,setDeviceInfo]=useState<Device|null>(null),[profilesOpen,setProfilesOpen]=useState(false);
 const [newName,setNewName]=useState(''),[newKind,setNewKind]=useState<'global'|'application'>('application');
 const draftRef=useRef(draft),snapshotRef=useRef(snapshot),busyRef=useRef(busy),requestSeq=useRef(0),pendingAction=useRef<null|(()=>void)>(null),preferredId=useRef<string|null>(null),closeRequested=useRef(false),refreshInFlight=useRef(false),nativeVisible=useRef(false),pollDelay=useRef(500);
 // A remembered identity can also be live, so retain explicit additions for this draft.
 const explicitRemembered=useRef(new Set<string>());
 draftRef.current=draft;snapshotRef.current=snapshot;busyRef.current=busy;
 useEffect(()=>{explicitRemembered.current.clear();},[draft?.original,draft?.profile.id]);
 const isDirty=useMemo(()=>dirty(draft),[draft]);
 useEffect(()=>{try{localStorage.setItem('hide-disconnected',hideDisconnected?'1':'0');}catch{}},[hideDisconnected]);
 useEffect(()=>{try{localStorage.setItem('hide-non-controllers',hideNonControllers?'1':'0');}catch{}},[hideNonControllers]);
 const refresh=useCallback(async()=>{
  if(busyRef.current||refreshInFlight.current||!nativeVisible.current)return;
  refreshInFlight.current=true;
  const seq=++requestSeq.current;
  try{const response=await api.request({command:'snapshot'});if(seq!==requestSeq.current)return;
   if(!response.ok||!response.snapshot)throw Error(response.error||'Profile engine did not return its state.');
   const next=response.snapshot,unchanged=same(snapshotRef.current,next);pollDelay.current=unchanged?Math.min(3000,pollDelay.current*2):500;snapshotRef.current=next;if(!unchanged)setSnapshot(next);setConnected(true);setConnectionAttempted(true);setConnectionError('');
   const current=draftRef.current;
   if(!dirty(current)){
    const p=next.profiles.find(p=>p.id===(preferredId.current||current?.profile.id))||next.profiles.find(p=>p.id===next.activeId)||next.profiles[0];
    if(p){const replacement=makeDraft(p,next);if(next.adoptionAwaitingSave&&next.adoptedSettings)replacement.settings=clone(next.adoptedSettings);if(!same(current,replacement)){draftRef.current=replacement;setDraft(replacement);}preferredId.current=null;}
   }
  }catch(e){if(seq===requestSeq.current){pollDelay.current=750;setConnected(false);setConnectionAttempted(true);setConnectionError(String(e instanceof Error?e.message:e));}}finally{refreshInFlight.current=false;}
 },[]);
 useEffect(()=>{
  let stopped=false,visibilityEventReceived=false,timer:ReturnType<typeof setTimeout>;
  const tick=async()=>{if(stopped)return;if(!document.hidden&&nativeVisible.current)await refresh();if(!stopped&&nativeVisible.current){clearTimeout(timer);timer=setTimeout(tick,pollDelay.current);}};
  const visible=()=>{if(!document.hidden&&nativeVisible.current){pollDelay.current=500;clearTimeout(timer);void tick();}};
  const setVisible=(value:boolean)=>{if(stopped)return;nativeVisible.current=value;document.documentElement.dataset.editorVisible=String(value);window.dispatchEvent(new Event('hidhide-visibility'));clearTimeout(timer);if(value)visible();};
  document.documentElement.dataset.editorVisible='false';
  const unsubscribe=api.onVisibility(value=>{visibilityEventReceived=true;setVisible(value);});void api.isVisible().then(value=>{if(!visibilityEventReceived)setVisible(value);}).catch(()=>{});
  void tick();document.addEventListener('visibilitychange',visible);window.addEventListener('focus',visible);
  return()=>{stopped=true;unsubscribe();clearTimeout(timer);document.removeEventListener('visibilitychange',visible);window.removeEventListener('focus',visible);};
 },[refresh]);
 useEffect(()=>{api.setDirty(isDirty||busy);},[isDirty,busy]);
 const guard=useCallback((action:()=>void)=>{if(busyRef.current)return;if(dirty(draftRef.current)){pendingAction.current=action;setModal('unsaved');}else action();},[]);
 useEffect(()=>api.onClose(()=>{if(busyRef.current){closeRequested.current=true;return;}guard(()=>api.close());}),[guard]);
 useEffect(()=>{if(!busy&&closeRequested.current){closeRequested.current=false;guard(()=>api.close());}},[busy,guard]);
 const updateProfile=(change:Partial<Profile>)=>setDraft(d=>d?{...d,profile:{...d.profile,...change}}:d);
 const updateSettings=(change:Partial<Draft['settings']>)=>setDraft(d=>d?{...d,settings:{...d.settings,...change}}:d);
 async function run(request:Record<string,unknown>){
  if(busyRef.current)return null;pollDelay.current=500;busyRef.current=true;setBusy(true);++requestSeq.current;setError('');setNotice('');
  try{const result=await api.request(request);if(!result.ok)throw Error(result.error||'The operation could not finish.');return result;}
  catch(e){setError(e instanceof Error?e.message:String(e));return null;}
  finally{busyRef.current=false;setBusy(false);}
 }
 async function save(){
  const d=draftRef.current,s=snapshotRef.current;if(!d||!s||!connected||!dirty(d))return false;
  const invalid=validation(d,s);if(invalid){setError(invalid);return false;}
  const result=await run(d.deleting?{command:'delete',id:d.profile.id,expected:d.expected,settings:d.settings,expectedSettings:d.expectedSettings}:same(d.profile,d.original)?{command:'settings',settings:d.settings,expectedSettings:d.expectedSettings}:{command:'apply',profile:d.profile,expected:d.expected,settings:d.settings,expectedSettings:d.expectedSettings});
  if(!result)return false;
  if(result.saved===false){setError(result.message||'Settings were not saved. Your changes are still open.');return false;}
  preferredId.current=d.deleting?null:d.profile.id;setDraft(null);draftRef.current=null;
  setNotice(result.message||'Settings saved.');await refresh();return true;
 }
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(!document.querySelector('dialog[open]'))void save();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 async function discard(){const state=snapshotRef.current;if(!state)return false;if(state.adoptionAwaitingSave){const result=await run({command:'abandon-adoption'});if(!result)return false;state.adoptionAwaitingSave=false;state.adoptedSettings=null;}const p=state.profiles.find(p=>p.id===draftRef.current?.profile.id)||state.profiles[0];const replacement=p?makeDraft(p,state):null;draftRef.current=replacement;setDraft(replacement);setError('');setNotice('Changes discarded.');return true;}
 async function pick(kind:Picker){try{return await api.pick(kind);}catch(e){setError(String(e));return null;}}
 async function create(){
  if(!newName.trim())return;let executable='';if(newKind==='application'){executable=await pick('executable')||'';if(!executable)return;}
  const result=await run({command:'new',kind:newKind,name:newName.trim(),executable});
  if(result?.profile&&snapshot){setDraft(makeDraft(result.profile,snapshot,true));setModal('');setSearch('');}
 }
 async function importProfile(){const path=await pick('import');if(!path)return;const result=await run({command:'import',path});if(result?.profile&&snapshot){setDraft(makeDraft(result.profile,snapshot,true));setSearch('');setNotice('Imported as a disabled copy. Review it before applying.');}}
 async function fileAction(kind:'backup'|'restore'|'export'){const path=await pick(kind);if(!path)return;const result=await run({command:kind,path,...(kind==='export'?{id:draft?.profile.id}:{})});if(result){setNotice(result.message||`${kind==='backup'?'Backup created':kind==='export'?'Saved profile exported':'Backup restored'}.`);if(kind==='restore'){setDraft(null);draftRef.current=null;await refresh();}setModal('');}}
 async function duplicate(){const draft=draftRef.current,snapshot=snapshotRef.current;if(!draft||!snapshot)return;const result=await run({command:'new',kind:draft.profile.kind,name:draft.profile.name+' copy',executable:draft.profile.executablePath});if(result?.profile){setDraft(makeDraft({...result.profile,enabled:false,deviceRules:clone(draft.profile.deviceRules),priority:draft.profile.priority},snapshot,true));setModal('');}}
 async function launch(){const d=draftRef.current,s=snapshotRef.current;if(!d||!s||dirty(d)||!d.expected||!s.settingsVersion)return;const result=await run({command:'launch',id:d.profile.id,expected:d.expected,expectedSettings:s.settingsVersion});if(result){await refresh();setNotice(result.message||'Application launched with its verified profile.');}}
 const filtered=snapshot?.profiles.filter(p=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))||[];
 const active=snapshot?.profiles.find(p=>p.id===snapshot.activeId);
 const rows=useMemo(()=>draft&&snapshot?deviceRows(draft.profile,draft.original,snapshot.devices):[],[draft?.profile,draft?.original,snapshot?.devices]);
 const connectionsKnown=connected&&!snapshot?.deviceError;
 const disconnectedCount=useMemo(()=>rows.filter(row=>!row.device.connected).length,[rows]);
 const nonControllerCount=useMemo(()=>rows.filter(row=>classifyDevice(row.device).controller==='non-game').length,[rows]);
 const visibleRows=useMemo(()=>filterDeviceRows(rows,hideDisconnected,!!connectionsKnown,hideNonControllers),[rows,hideDisconnected,connectionsKnown,hideNonControllers]);
 const filteredCount=rows.length-visibleRows.length;
 const devices=useMemo(()=>rows.map(row=>row.device),[rows]);
 const invalid=draft&&snapshot?validation(draft,snapshot):'';
 const stale=draft&&snapshot&&(draft.expected&&snapshot.profiles.find(p=>p.id===draft.profile.id)?.version?.hash!==draft.expected.hash||snapshot.settingsVersion?.hash!==draft.expectedSettings?.hash);
 const editingActive=!!draft&&snapshot?.verified&&snapshot.activeId===draft.profile.id&&!draft.settings.paused;
 const select=(p:Snapshot['profiles'][number])=>guard(()=>{const latest=snapshotRef.current,target=latest?.profiles.find(item=>item.id===p.id);if(latest&&target){setDraft(makeDraft(target,latest));setProfilesOpen(false);setNotice('');setError('');}});
 const currentDevice=deviceInfo?(devices.find(device=>device.id===deviceInfo.id)||{...deviceInfo,connected:false,current:'Unknown' as const}):null;
 return <div className="app-shell" aria-busy={busy}>
  <header className="engine-bar"><button className="compact-profiles" aria-expanded={profilesOpen} aria-controls="profiles-sidebar" onClick={()=>setProfilesOpen(value=>!value)}>Profiles</button><div className="engine-summary"><span className={'engine-symbol '+(connected&&snapshot?.verified?'':'uncertain')}><Shield size={25}/></span><div><strong>{!connected?(connectionAttempted?'Profile engine unavailable':'Connecting to profile engine…'):snapshot?.verified?'Profile engine running':'Profile engine needs attention'}</strong><p>{!connected?'Current policy is unknown':snapshot?.settings.paused?'Hiding is paused':snapshot?.verified?`Active profile: ${active?.name||'Global'}`:'Applied state has not been verified'}</p></div></div>
   <div className="theme-control"><button className="theme-toggle" aria-label={theme==='dark'?'Switch to light mode':'Switch to dark mode'} disabled={themeSaving} onClick={()=>void toggleTheme()}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}<span>{theme==='dark'?'Light mode':'Dark mode'}</span></button></div>
   {draft&&<div className="engine-controls"><fieldset className="segments" disabled={busy||!connected||!!snapshot?.launchedId}><legend className="sr-only">Profile mode</legend>{(['automatic','useGlobal'] as const).map(mode=><label key={mode}><input type="radio" name="mode" checked={draft.settings.mode===mode} onChange={()=>updateSettings({mode})}/><span>{mode==='automatic'?'Automatic':'Use Global'}</span></label>)}</fieldset><label className="fallback">Global fallback<select value={draft.settings.selectedGlobalId} disabled={busy||!connected||!!snapshot?.launchedId} onChange={e=>updateSettings({selectedGlobalId:e.target.value})}>{snapshot?.profiles.filter(p=>p.kind==='global'&&p.enabled).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy||!connected||!!snapshot?.launchedId} onClick={()=>updateSettings({paused:!draft.settings.paused})}>{draft.settings.paused?'Resume hiding':'Pause hiding'}</button></div>}
  </header>
  <aside id="profiles-sidebar" className={"sidebar "+(profilesOpen?"compact-open":"")} aria-label="Profiles"><div className="sidebar-heading"><h2>Profiles</h2><button className="icon" aria-label="New profile" disabled={busy||!connected} onClick={()=>guard(()=>{setNewName('');setModal('new');})}><Plus size={21}/></button></div><label className="search"><Search size={18}/><span className="sr-only">Find a profile</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a profile" type="search"/></label><nav aria-label="Profile selection" className="profile-list">{(['global','application'] as const).map(kind=><section key={kind}><h3>{kind==='global'?'Global':'Applications'}</h3>{filtered.filter(p=>p.kind===kind).map(p=><button className={'profile-item '+(draft?.profile.id===p.id?'selected':'')} key={p.id} aria-current={draft?.profile.id===p.id?'page':undefined} onClick={()=>select(p)} disabled={busy}><span className="profile-glyph">{p.kind==='global'?<Shield size={19}/>:<ApplicationIcon path={p.executablePath} size={22}/>}</span><span className="profile-name">{p.name}<small>{!p.enabled?'Disabled':p.missing?'Application missing':p.running?'Running':''}</small></span><small className="row-state">{connected&&snapshot?.verified&&snapshot.activeId===p.id?'Active':dirty(draft)&&draft?.profile.id===p.id?'Edited':''}</small></button>)}</section>)}{!filtered.length&&<p className="empty-small">No profiles match “{search}”.</p>}{draft&&!draft.original&&<p className="draft-note">Editing new profile: {draft.profile.name}</p>}</nav><footer className="rail-actions"><button onClick={()=>guard(()=>void importProfile())} disabled={!connected||busy}><Download/>Import profiles</button><button onClick={()=>void fileAction('backup')} disabled={!connected||busy}><Upload/>Back up profiles</button><button onClick={()=>{void api.openFolder().then(message=>{if(message)setError(message);});}}><FolderOpen/>Open profiles folder</button><button onClick={()=>setModal('settings')} disabled={busy}><SettingsIcon/>Settings</button></footer></aside>
  <main className="workspace"><div className="editor-scroll">
   {themeError&&<div className="banner error" role="alert"><AlertCircle/><p>{themeError}</p></div>}
   {!connected&&connectionAttempted&&<div className="banner error" role="alert"><AlertCircle/><div><strong>Cannot connect to the profile engine</strong><p>{connectionError||'Waiting for the native profile engine.'}</p><button onClick={()=>void refresh()} disabled={busy}><RefreshCw size={15}/>Reconnect</button></div></div>}
   {connected&&error&&<div className="banner error" role="alert"><AlertCircle/><div><strong>Could not complete the operation</strong><p>{error}</p></div><button className="icon" aria-label="Dismiss error" onClick={()=>setError('')}><X/></button></div>}
   {notice&&<div className="banner notice" role="status"><Check/><p>{notice}</p></div>}
   {snapshot&&(snapshot.conflict||snapshot.repositoryIssues.length>0||!snapshot.verified)&&connected&&<div className="banner warning"><AlertCircle/><div><strong>{snapshot.conflict?'Driver settings need review':snapshot.repositoryIssues.length?'Profile files need attention':'Activation is not verified'}</strong><p>{snapshot.status}</p>{snapshot.repositoryIssues.map((issue,i)=><p key={i}>{typeof issue==='string'?issue:JSON.stringify(issue)}</p>)}<div className="actions"><button disabled={busy} onClick={async()=>{const r=await run({command:'retry'});if(r){setNotice(r.message||'Activation checked.');await refresh();}}}>Retry activation</button>{snapshot.conflict&&<button onClick={()=>setModal('recovery')}>Review recovery</button>}</div></div></div>}
   {stale&&isDirty&&<div className="banner warning" role="status"><AlertCircle/><p>Saved files changed while you were editing. Your draft is preserved. Discard to reload; Apply will check for conflicts.</p></div>}
   {draft?<><div className="editor-heading"><div><h1>{draft.profile.name||'Untitled profile'}</h1><p>{draft.profile.kind==='application'?'Device visibility when this application is running':'Device visibility used as your Global policy'}</p></div><button className="icon" aria-label="Profile actions" onClick={()=>setModal('profile')} disabled={busy}><MoreVertical/></button></div>
    {draft.profile.kind==='application'&&<section className="application-card"><span className="app-icon"><ApplicationIcon path={draft.profile.executablePath} size={38}/></span><div><span className="eyebrow">Matched application</span><strong>{basename(draft.profile.executablePath)}</strong><button className="text path" onClick={()=>setModal('path')}>View executable path <ChevronRight size={14}/></button><small>Launch directly after the saved profile is verified. Close any running copy first.</small></div><button disabled={busy||!!snapshot?.launchedId} onClick={async()=>{const path=await pick('executable');if(path)updateProfile({executablePath:path});}}>Change app</button><button disabled={busy||!connected||!!snapshot?.launchedId||!draft.original||!draft.profile.enabled||!!draft.deleting||isDirty||!!snapshot?.profiles.find(p=>p.id===draft.profile.id)?.missing||!!snapshot?.settings.paused||!!snapshot?.conflict||!!snapshot?.repositoryIssues.length||!draft.expected||!snapshot?.settingsVersion} onClick={()=>guard(()=>void launch())}>Launch with profile</button></section>}
    <section className="devices-section"><div className="section-heading"><h2>Device visibility</h2><span>{!connected||snapshot?.deviceError?'Connection unknown':`${snapshot?.devices.filter(d=>d.connected).length||0} connected`}</span><button className="icon" aria-label="Device visibility help" onClick={()=>setModal('help')}><CircleHelp size={17}/></button></div><div className="device-filter"><button className="filter-toggle" aria-label="Hide disconnected" aria-pressed={hideDisconnected} disabled={!connectionsKnown} onClick={()=>setHideDisconnected(value=>!value)}>Hide disconnected{connectionsKnown?` (${disconnectedCount})`: ""}</button><button className="filter-toggle" aria-label="Hide non-game controllers" aria-pressed={hideNonControllers} onClick={()=>setHideNonControllers(value=>!value)}>Hide non-game controllers ({nonControllerCount})</button><span role="status">{filteredCount>0?`${filteredCount} ${filteredCount===1?'device':'devices'} hidden from view. `:''}View filters only; profile rules stay unchanged.{hideNonControllers?' Unknown controller types stay visible.':' '}</span></div><p className="section-description">Choose which devices are hidden from games. Allowed apps can still access them.</p>
     {snapshot?.deviceError&&<div className="banner warning" role="status"><AlertCircle/><p>Device connections could not be refreshed: {snapshot.deviceError}. Remembered rules remain available.</p></div>}<div className="device-table" role="table" aria-label="Device visibility"><div className="device-header" role="row"><span role="columnheader">Device</span><span role="columnheader">Applied now</span><span role="columnheader">Profile rule</span></div>{visibleRows.map(({device:d,value,changed})=>{const classification=classifyDevice(d);return <div role="row" className="device-row" key={d.id}><div role="cell" className="device-name"><DeviceIcon device={d} size={30}/><div><strong>{d.name}</strong><small className="device-classification" title={classification.reason}>{classification.label} · {controllerLabel(classification.controller)}</small><small>{!connected||snapshot?.deviceError?'Connection unknown':d.connected?'Connected device':'Remembered · not connected'}</small><button className="text" onClick={()=>{setDeviceInfo(d);setModal('device');}}>Device details</button></div></div><div role="cell" className="applied"><span className="mobile-label">Applied now</span>{connected?d.current:'Unknown'}</div><div role="cell" className="rule"><fieldset className="segments" disabled={busy||draft.deleting||!connected}><legend className="sr-only">Visibility for {d.name}</legend>{(['visible','hidden'] as const).map(v=><label key={v}><input type="radio" name={'device-'+d.id} checked={value===v} onChange={()=>updateProfile(setVisibility(draft.profile,d,v,draft.original,explicitRemembered.current))}/><span>{v==='visible'?'Visible':'Hidden'}</span></label>)}</fieldset>{value==='mixed'&&<small>Mixed rules</small>}{changed&&<span className="change-mark" aria-label="Changed" title="Changed">•</span>}</div></div>;})}{!visibleRows.length&&<div className="empty-state"><h3>{filteredCount?'No devices match these filters':'No devices to display'}</h3><p>{filteredCount?'Show all devices to view their saved rules.':'Connect a device or add a remembered device identity.'}</p>{filteredCount>0&&<button onClick={()=>{setHideDisconnected(false);setHideNonControllers(false);}}>Show all devices</button>}</div>}</div><button className="text remembered" disabled={busy} onClick={()=>setModal('remembered')}><Plus size={15}/>Add remembered device</button>
    </section><section className="allowed-section"><div><h2>Allowed apps <small>Global</small></h2><p>Always able to read hidden devices</p><div className="chips">{draft.settings.allowedApplications.length?draft.settings.allowedApplications.map(path=><span className="chip" key={path} title={path}>{basename(path)}</span>):<span className="muted">No apps allowed yet</span>}</div></div><button disabled={busy} onClick={()=>setModal('allowed')}>Manage allowed apps</button></section>
   </>:connected?<div className="empty-state"><Shield/><h1>No editable profile</h1><p>Review the profile file diagnostics or restore a backup in Settings.</p></div>:<div className="empty-state"><Activity/><h1>Connecting to HidHide</h1><p>Your saved profiles are managed by the native profile engine.</p></div>}
  </div><footer className={'save-bar '+(isDirty?'pending':'')}><div><strong>{draft?.deleting?'Profile marked for deletion':isDirty?`${draft?pendingCount(draft):0} pending ${draft&&pendingCount(draft)===1?'change':'changes'}`:'No pending changes'}</strong><p>{snapshot?.launchedId?'The directly launched application holds its profile until it exits. Close it before changing settings.':invalid&&isDirty?invalid:isDirty?'Saved settings apply according to the selected mode and active profile.':'Saved profiles stay available when the editor is closed.'}</p></div><div className="actions"><button disabled={!isDirty||busy} onClick={discard}>Discard</button><button className="primary" disabled={!isDirty||busy||!connected||!!invalid||!!snapshot?.launchedId} onClick={()=>void save()}>{busy?'Working…':draft?.deleting?'Delete profile':'Apply changes'}</button></div></footer></main>
  <footer className="status-bar"><span>{connected?<Check size={16}/>:<AlertCircle size={16}/>} {connected?'Closing this window keeps profiles running.':'Engine connection unavailable. Applied state is unknown.'}</span><button className="text" onClick={()=>guard(()=>api.close())} disabled={busy}>Close editor</button></footer>
  {modal==='unsaved'&&<Modal title="Keep your changes?" onClose={()=>{pendingAction.current=null;setModal('');}}><p>You have unapplied changes. Apply them, discard them, or keep editing.</p><div className="dialog-actions"><button onClick={()=>{pendingAction.current=null;setModal('');}}>Keep editing</button><button disabled={busy} onClick={async()=>{if(await discard()){const action=pendingAction.current;pendingAction.current=null;setModal('');action?.();}}}>Discard changes</button><button className="primary" disabled={busy||!connected||!!invalid} onClick={async()=>{if(await save()){const action=pendingAction.current;pendingAction.current=null;setModal('');action?.();}}}>Apply changes</button></div>{error&&<p role="alert" className="error-text">{error}</p>}{invalid&&<p className="error-text">{invalid}</p>}</Modal>}
  {modal==='new'&&<Modal title="New profile" onClose={()=>setModal('')}><label className="field">Profile name<input autoFocus maxLength={256} value={newName} onChange={e=>setNewName(e.target.value)}/></label><label className="field">Profile type<select value={newKind} onChange={e=>setNewKind(e.target.value as typeof newKind)}><option value="application">Application</option><option value="global">Global</option></select></label><p className="muted">{newKind==='application'?'Choose the exact executable to match.':'A Global profile can be selected as your fallback.'} The new profile is saved only when you apply.</p><div className="dialog-actions"><button onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={!newName.trim()||busy} onClick={()=>void create()}>{newKind==='application'?'Choose application':'Create draft'}</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</Modal>}
  {modal==='profile'&&draft&&<Modal title="Profile details" onClose={()=>setModal('')}><label className="field">Name<input maxLength={256} value={draft.profile.name} onChange={e=>updateProfile({name:e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={draft.profile.enabled} onChange={e=>updateProfile({enabled:e.target.checked})}/>Enable this profile</label>{draft.profile.kind==='application'&&<label className="field">Priority<input type="number" min={-100000} max={100000} value={draft.profile.priority} onChange={e=>updateProfile({priority:Number(e.target.value)})}/><small>Higher priority wins when multiple applications match.</small></label>}<div className="menu-actions"><button onClick={()=>guard(()=>void duplicate())} disabled={busy}><Copy size={17}/>Duplicate as disabled draft</button><button onClick={()=>void fileAction('export')} disabled={!draft.original||busy}><FileJson size={17}/>Export saved profile</button><button className="danger" disabled={!draft.original||busy} onClick={()=>{setDraft(d=>d?{...d,deleting:!d.deleting}:d);setModal('');}}><Trash2 size={17}/>{draft.deleting?'Undo deletion':'Mark for deletion'}</button></div><p className="muted">Edits are staged until Apply. Deleting the selected Global requires another fallback.</p><div className="dialog-actions"><button onClick={()=>setModal('')}>Done</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</Modal>}
  {modal==='settings'&&<Modal title="Settings & recovery" onClose={()=>setModal('')}>{draft&&<label className="check-field"><input type="checkbox" checked={draft.settings.startWithWindows} onChange={e=>updateSettings({startWithWindows:e.target.checked})}/>Start the profile engine with Windows</label>}<p>The editor opens only when you request it. Automatic profiles continue in the background.</p><div className="menu-actions"><button disabled={busy} onClick={()=>void fileAction('backup')}><Upload size={17}/>Back up saved profiles</button><button disabled={busy} onClick={()=>guard(()=>setModal('restore'))}><Download size={17}/>Restore a backup…</button></div><p className="muted">Startup changes are staged until Apply. To stop monitoring and restore the baseline, use Exit in the native tray menu.</p><div className="dialog-actions"><button onClick={()=>setModal('')}>Done</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</Modal>}
  {modal==='restore'&&<Modal title="Restore saved profiles?" onClose={()=>setModal('')}><p>This replaces the saved profile catalog with the selected backup. Back up your current profiles first if you want to keep them.</p><div className="dialog-actions"><button onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void fileAction('restore')}>Choose backup folder</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</Modal>}
  {modal==='allowed'&&draft&&<Modal title="Allowed apps" onClose={()=>setModal('')} wide><p>These global exceptions can read hidden devices in every profile. Keep feeders such as SimHub allowed.</p><ul className="path-list">{draft.settings.allowedApplications.map(path=><li key={path}><span>{path}</span><button className="icon" aria-label={'Remove '+basename(path)} onClick={()=>updateSettings({allowedApplications:draft.settings.allowedApplications.filter(p=>p!==path)})}><X size={18}/></button></li>)}</ul>{!draft.settings.allowedApplications.length&&<p className="muted">No allowed applications.</p>}<div className="dialog-actions"><button onClick={async()=>{const path=await pick('executable');if(path&&!draft.settings.allowedApplications.some(p=>p.toLowerCase()===path.toLowerCase()))updateSettings({allowedApplications:[...draft.settings.allowedApplications,path]});}}><Plus size={17}/>Add application</button><button onClick={()=>setModal('')}>Done</button></div><small>Changes are staged until Apply.</small>{error&&<p role="alert" className="error-text">{error}</p>}</Modal>}
  {modal==='path'&&draft&&<Modal title="Matched executable" onClose={()=>setModal('')} wide><p className="path-value">{draft.profile.executablePath}</p><p>Automatic matching uses this exact executable path.</p></Modal>}
  {modal==='device'&&currentDevice&&<Modal title={currentDevice.name} onClose={()=>setModal('')} wide><p>{!connected||snapshot?.deviceError?'Connection unknown':currentDevice.connected?'Connected':'Remembered, currently disconnected'} · Applied now: {connected?currentDevice.current:'Unknown'}</p><p><strong>{classifyDevice(currentDevice).label} · {controllerLabel(classifyDevice(currentDevice).controller)}</strong></p><p>{classifyDevice(currentDevice).reason}</p><p>Visibility applies to each interface below.</p><ul className="path-list">{currentDevice.identities.map(id=><li key={id}><code>{id}</code></li>)}</ul></Modal>}
  {modal==='remembered'&&draft&&<Modal title="Add remembered device" onClose={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),identity=String(form.get('identity')).trim(),name=String(form.get('name')).trim();if(!identity)return;if(draft.profile.deviceRules.some(r=>r.identity.toLowerCase()===identity.toLowerCase())){setError('This identity already exists in the profile.');return;}explicitRemembered.current.add(identity.toLowerCase());updateProfile({deviceRules:[...draft.profile.deviceRules,{identity,friendlyName:name,visibility:'visible'}]});setHideDisconnected(false);setModal('');}}><label className="field">Friendly name<input name="name" maxLength={1024}/></label><label className="field">Exact device identity<input name="identity" required maxLength={32768}/></label><p>Use an exact device identity from Device details. It starts visible until you change its rule.</p><div className="dialog-actions"><button type="button" onClick={()=>setModal('')}>Cancel</button><button className="primary" type="submit">Add to draft</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</form></Modal>}
  {modal==='help'&&<Modal title="How device visibility works" onClose={()=>setModal('')}><p><strong>Applied now</strong> is the observed driver state. <strong>Profile rule</strong> is the policy saved by Apply. An inactive profile takes effect only when selected by the profile engine.</p><p>Hidden devices remain available to Allowed apps. Disconnected or unverified devices may show Unknown. Mixed means the device interfaces have different rules.</p></Modal>}
  {modal==='recovery'&&<Modal title="Review driver recovery" onClose={()=>setModal('')}><p>Another configuration change or interrupted operation needs review. You can accept the currently observed settings as the restoration baseline. This does not replace your saved profiles.</p><p>Back up your profiles before proceeding if you are unsure. Any observed Allowed apps will be staged for review.</p><div className="dialog-actions"><button onClick={()=>setModal('')}>Cancel</button><button disabled={busy} onClick={()=>guard(async()=>{const expectedSettings=snapshotRef.current?.settingsVersion;if(!expectedSettings){setError('Settings must be readable before accepting a baseline.');return;}const r=await run({command:'adopt',expectedSettings});if(r){if(r.needsApply&&r.settings)setDraft(d=>d?{...d,settings:clone(r.settings!)}:d);setNotice(r.message||'Observed baseline accepted. Review settings before applying.');await refresh();setModal('');}})}>Accept observed baseline</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</Modal>}
 </div>;
}
void api.getTheme().catch(()=>'dark' as const).then(initialTheme=>{document.documentElement.dataset.theme=initialTheme;createRoot(document.getElementById('root')!).render(<App initialTheme={initialTheme}/>);});
