<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion><ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable><PlatformTarget>x64</PlatformTarget>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Installer/HidHide.Installer.csproj" />
    <Compile Include="../../Installer/MaintenanceUser.cs" Link="MaintenanceUser.cs" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
