import {_electron as electron,expect} from '@playwright/test';
import path from 'node:path';
import fs from 'node:fs/promises';
const root=path.resolve(import.meta.dirname,'..'),env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
const output=path.resolve(root,'../artifacts/application-picker');await fs.mkdir(output,{recursive:true});
const app=await electron.launch({args:[root,'--fixture'],env,timeout:30000});
try{
 const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const control=options=>app.evaluate((_electron,value)=>globalThis.__fixtureControl(value),options);
 const open=async()=>{await page.getByRole('button',{name:'New profile',exact:true}).click();};
 const browse=()=>page.getByRole('button',{name:'Browse for EXE',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Le Mans Ultimate',exact:true})).toBeVisible();
 await open();await expect(page.getByLabel('Profile name',{exact:true})).toHaveCount(0);
 await browse();await expect(page.getByLabel('Profile name',{exact:true})).toHaveValue('New game');
 await page.getByLabel('Profile name',{exact:true}).fill('My racing profile');
 await control({discovery:{path:'D:\\Games\\Second.exe'}});await browse();
 await expect(page.getByLabel('Profile name',{exact:true})).toHaveValue('My racing profile');
 await control({discovery:{delay:450,createDelay:450}});
 await page.getByRole('button',{name:'Create draft',exact:true}).click();
 await expect(page.getByLabel('Profile name',{exact:true})).toBeDisabled();
 await expect(page.getByLabel('Profile type')).toBeDisabled();
 await expect(page.locator('.app-shell')).toHaveAttribute('aria-busy','true');
 await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByRole('heading',{name:'My racing profile',exact:true})).toBeVisible();
 await control({discovery:{delay:0,createDelay:0}});
 let state=await control({});if(state.profiles.some(p=>p.name==='My racing profile'))throw Error('Draft saved before Apply.');
 await page.getByRole('button',{name:'Discard',exact:true}).click();
 await open();await page.getByRole('button',{name:'Choose running application',exact:true}).click();
 const rows=page.locator('.running-applications button');await expect(rows).toHaveCount(2);
 await page.screenshot({path:path.join(output,'running-list.png')});
 await expect(rows.first()).toContainText('2 instances');await expect(page.getByRole('dialog')).toContainText('2 processes unavailable');
 await page.getByLabel('Find running application').fill('D:\\Tools');await expect(rows).toHaveCount(1);await expect(rows.first()).toContainText('Background app');
 await rows.first().click();await expect(page.getByLabel('Profile name',{exact:true})).toHaveValue('Background Game');
 await page.screenshot({path:path.join(output,'selected-application.png')});
 await app.browserWindow(page).then(w=>w.evaluate(window=>window.setSize(600,560)));
 await page.getByRole('button',{name:'Create draft',exact:true}).scrollIntoViewIfNeeded();
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Compact picker overflows horizontally.');
 await page.screenshot({path:path.join(output,'selected-compact.png')});
 await app.browserWindow(page).then(w=>w.evaluate(window=>window.setSize(1320,900)));
 await control({discovery:{fail:'This application has exited or changed.'}});
 await page.getByRole('button',{name:'Create draft',exact:true}).click();await expect(page.getByRole('alert')).toContainText('exited');
 await expect(page.getByLabel('Profile name',{exact:true})).toBeEnabled();
 await expect(page.getByLabel('Profile type')).toBeEnabled();
 await control({discovery:{fail:'',delay:450}});
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await page.getByLabel('Profile type').selectOption('global');await page.getByLabel('Profile name',{exact:true}).fill('Global manual');
 await page.waitForTimeout(600);await expect(page.getByLabel('Profile name',{exact:true})).toHaveValue('Global manual');await expect(rows).toHaveCount(0);
 await page.getByRole('button',{name:'Create draft',exact:true}).click();await expect(page.getByRole('heading',{name:'Global manual',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Discard',exact:true}).click();
 await control({discovery:{delay:0}});await open();await browse();
 await expect(page.getByLabel('Profile name',{exact:true})).toBeVisible();
 await control({discovery:{delay:450}});await page.getByRole('button',{name:'Create draft',exact:true}).click();
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.waitForTimeout(600);await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Apply changes',exact:true})).toBeDisabled();
 await open();await browse();await page.getByRole('button',{name:'Cancel',exact:true}).click();await open();
 await control({discovery:{delay:0,path:'C:\\Games\\Latest.exe'}});await browse();
 await expect(page.getByLabel('Profile name',{exact:true})).toHaveValue('Latest');await page.waitForTimeout(600);
 await expect(page.getByLabel('Profile name',{exact:true})).toHaveValue('Latest');
 await page.getByRole('button',{name:'Create draft',exact:true}).click();
 await page.getByRole('button',{name:'Apply changes',exact:true}).click();
 state=await control({});if(!state.profiles.some(p=>p.name==='Latest'&&p.executablePath==='C:\\Games\\Latest.exe'))throw Error('Apply did not persist selected executable and name.');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS application picker: app-first browse, manual name preservation, detached draft/discard/Apply, grouped/searchable running apps, exited selection, type-change and close/reopen stale responses.');
}finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});}
